version: "3"
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    volumes:
      - ./typecho:/usr/share/nginx/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      # - "443:443"
    depends_on:
      - php
  php:
    build: ./docker/php
    volumes:
      - ./typecho:/var/www/html:rw
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    # restart: always
    command: 'mysqld --innodb-flush-method=fsync'
    environment:
      # MYSQL_ROOT_PASSWORD: typecho-db-passwd
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_USER: typecho
      MYSQL_PASSWORD: typecho-db-passwd
      MYSQL_DATABASE: typecho
    volumes:
      - ./data:/var/lib/mysql:rw

